// This file is generated by .github/workflows/update-build-info.yml
// It sets window globals used by the game to display build metadata.
window.BUILD_VERSION = 'c28680a';
window.BUILD_COMMIT = 'c28680a5d7a45cfbf1695c29d60681b5e8f789c5';
window.BUILD_COMMIT_TIME = '2025-10-14T12:22:08+01:00';
