// This file is generated by .github/workflows/update-build-info.yml
// It sets window globals used by the game to display build metadata.
window.BUILD_VERSION = 'abad4e5';
window.BUILD_COMMIT = 'abad4e5e0bc630c86d65061192d712ed4a897622';
window.BUILD_COMMIT_TIME = '2025-12-31T22:35:34Z';
