// This file is generated by .github/workflows/update-build-info.yml
// It sets window globals used by the game to display build metadata.
window.BUILD_VERSION = '5b7b232';
window.BUILD_COMMIT = '5b7b232da1e42fb393d068fcfbce25c1f64ade24';
window.BUILD_COMMIT_TIME = '2025-10-16T10:00:11+01:00';
