name: Update build info

on:
  push:
    branches: [ main ]
    # ignore changes to the generated build-info file to avoid loops
    paths-ignore:
      - 'games-HTML5/zombie-shooter/build-info.js'

# Allow this workflow to push changes back to the repository
permissions:
  contents: write

jobs:
  write-build-info:
    # Use a self-hosted runner so jobs run immediately on your machine (free runner)
    # Make sure you have a self-hosted runner registered for this repository with the label 'self-hosted'
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # ensure the runner has the commit refs and allow pushing
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get git metadata
        id: gitmeta
        run: |
          echo "SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "FULL=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "TIME=$(git log -1 --format=%cI)" >> $GITHUB_OUTPUT
          # Try to find the latest annotated or lightweight tag; prefer semver-like tags
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || true)
          if [ -n "$TAG" ]; then
            echo "VERSION=$TAG" >> $GITHUB_OUTPUT
          else
            echo "VERSION=$((git rev-parse --short HEAD))" >> $GITHUB_OUTPUT
          fi

      - name: Create build-info.js
        run: |
          mkdir -p games-HTML5/zombie-shooter
          cat > games-HTML5/zombie-shooter/build-info.js <<'JS'
          // This file is generated by .github/workflows/update-build-info.yml
          // It sets window globals used by the game to display build metadata.
          window.BUILD_VERSION = '${{ steps.gitmeta.outputs.VERSION }}';
          window.BUILD_COMMIT = '${{ steps.gitmeta.outputs.FULL }}';
          window.BUILD_COMMIT_TIME = '${{ steps.gitmeta.outputs.TIME }}';
          JS

      - name: Upload build-info artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-info-zombie-shooter
          path: games-HTML5/zombie-shooter/build-info.js
